services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASS=amc123
      - DB_NAME=projet_db
      - DB_PORT=3306

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: amc123
      MYSQL_DATABASE: "projet_db"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
